# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'UpitnikDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UpitnikDemo
pod 'SnapKit', '~> 4.0.0'

end
